### ISSUE TITLE
Failure during install

### ISSUE THREAD

**Issue by bkmeneguello** [jenkinsci/uithemes-plugin#1]
SEVERE: Failed to install UIThemes: Plugin
java.lang.NoSuchMethodError: org.jenkins.ui.icon.Icon.setUseCSSRendering(Z)Lorg/jenkins/ui/icon/Icon;
    at org.jenkinsci.plugins.uithemes.UIThemesPlugin.postInitialize(UIThemesPlugin.java:41)
    at hudson.PluginManager.dynamicLoad(PluginManager.java:465)
    at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1313)
    at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1116)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:104)
    at java.lang.Thread.run(Thread.java:745)

During instalation on latest version

**Comment by tfennelly** [comment]
@bkmeneguello thanks for trying it, but why did you try it this way as opposed to installing the version of Jenkins that's linked to in the top level readme?

Anyway, this plugin will eventually have a min dependency on a version of Jenkins that has the correct version of the icon-shim-plugin. So from that point of view, it's really a WIP (yeah the versioning is a bit whackie but that'll sort itself out in time).

**Comment by tfennelly** [comment]
Closing this issue. Added a comment to the readme.
